# Generated by Django 5.1.7 on 2025-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_verified_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
